apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sinfonia-tier2.fullname" . }}
  labels:
    {{- include "sinfonia-tier2.labels" . | nindent 4 }}
spec:
  {{- if .Values.runtimeClassName }}
  runtimeClassName: {{ .Values.runtimeClassName }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sinfonia-tier2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sinfonia-tier2.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imageCredentials }}
      imagePullSecrets:
        - name: {{ include "sinfonia-tier2.fullname" }}-docker-registry
      {{- end }}
      serviceAccountName: {{ include "sinfonia-tier2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if and .Values.sinfoniaTier1Url .Values.sinfoniaTier2Url }}
            - name: SINFONIA_TIER1_URL
              value: {{ .Values.sinfoniaTier1Url }}
            - name: SINFONIA_TIER2_URL
              value: {{ .Values.sinfoniaTier2Url }}
            {{- end }}
            {{- if and .Values.sinfoniaTier2Latitude .Values.sinfoniaTier2Longitude }}
            - name: SINFONIA_TIER2_LATITUDE
              value: "{{ .Values.sinfoniaTier2Latitude }}"
            - name: SINFONIA_TIER2_LONGITUDE
              value: "{{ .Values.sinfoniaTier2Longitude }}"
            {{- end }}   
            {{- if and .Values.sinfoniaTier3Latitude .Values.sinfoniaTier3Longitude }}
            - name: SINFONIA_TIER3_LATITUDE
              value: "{{ .Values.sinfoniaTier3Latitude }}"
            - name: SINFONIA_TIER3_LONGITUDE
              value: "{{ .Values.sinfoniaTier3Longitude }}"
            {{- end }}
            {{- if and .Values.sinfoniaTier2Zone }}
            - name: SINFONIA_TIER2_ZONE
              value: {{ .Values.sinfoniaTier2Zone }}
            {{- end }} 
            {{- if and .Values.sinfoniaKubeConfig }}
            - name: SINFONIA_KUBECONFIG
              value: {{ .Values.sinfoniaKubeConfig }}
            {{- end }} 
            {{- if and .Values.sinfoniaKubeContext }}
            - name: SINFONIA_KUBECONTEXT
              value: {{ .Values.sinfoniaKubeContext }}
            {{- end }} 
            {{- if and .Values.sinfoniaPrometheus }}
            - name: SINFONIA_PROMETHEUS
              value: {{ .Values.sinfoniaPrometheus }}
            {{- end }}
            - name: SINFONIA_RECIPES
              value: {{ .Values.sinfoniaRecipesMountPath }}
            {{- if and .Values.experimentObelixNodeName }}
            - name: EXPERIMENT_OBELIX_NODE_NAME
              value: {{ .Values.experimentObelixNodeName }}
            {{- end }}
            {{- if and .Values.experimentPowerMeasureMethod }}
            - name: EXPERIMENT_POWER_MEASURE_METHOD
              value: {{ .Values.experimentPowerMeasureMethod }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: recipes
              mountPath: {{ .Values.sinfoniaRecipesMountPath }}
              readOnly: true
      volumes:
        - name: recipes
          hostPath:
            path: {{ .Values.sinfoniaRecipes }}
            type: Directory
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
