apiVersion: v1
kind: Service
metadata:
  name: {{ include "imgc-resnet50-onnx.fullname" . }}
  labels:
    {{- include "imgc-resnet50-onnx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: grpc
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: metrics
  selector:
    {{- include "imgc-resnet50-onnx.selectorLabels" . | nindent 4 }}
