apiVersion: v1
kind: Service
metadata:
  name: {{ include "imgc-resnet50-onnx.fullname" . }}
  labels:
    {{- include "imgc-resnet50-onnx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: http
      name: http-inference-server
    - port: 8001
      targetPort: grpc
      name: grpc-inference-server
    - port: 8002
      targetPort: metrics
      name: metrics-inference-server
  selector:
    {{- include "imgc-resnet50-onnx.selectorLabels" . | nindent 4 }}
