apiVersion: v1
kind: Service
metadata:
  name: {{ include "imgc-resnet50-onnx.fullname" . }}
  labels:
    {{- include "imgc-resnet50-onnx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      name: http-inference-server
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      name: grpc-inference-server
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      name: metrics-inference-server
  selector:
    {{- include "imgc-resnet50-onnx.selectorLabels" . | nindent 4 }}
