apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadtest-port30137.fullname" . }}
  labels:
    {{- include "loadtest-port30137.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "loadtest-port30137.selectorLabels" . | nindent 4 }}
